@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kazi_cat.papercraft_magic_decoration.datagen.builder;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;