@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kazi_cat.papercraft_magic_decoration.item.tool;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;