@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kazi_cat.papercraft_magic_decoration.block.food.smeltable;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;