@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kazi_cat.papercraft_magic_decoration.compat.ponder.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;