@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.kazi_cat.papercraft_magic_decoration.compat.jei.category;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;